'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmployeeInfo

    '''<summary>
    '''tb_employeeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_employeeId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchEmployee As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tb_employeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_employeeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_EmployeeStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_EmployeeStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AccountStatusApproveBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountStatusApproveBtn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''AccountStatusPendingBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountStatusPendingBtn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''AccountStatusFreezBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountStatusFreezBtn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ASPxRoundPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel1 As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''ASPxImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxImage1 As Global.DevExpress.Web.ASPxImage

    '''<summary>
    '''tb_userid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_userid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_fathername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_fathername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_DOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_DOB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb_gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_gender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cb_bloodGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_bloodGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tb_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_address2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_address2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_mobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_mobile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_mobile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_mobile2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_aadhaar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_aadhaar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_pan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_pan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_pran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_pran As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_remarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ASPxRoundPanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel3 As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''tb_joindate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_joindate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_retair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_retair As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_post control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_post As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_trca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_trca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_originalPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_originalPost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_currentPlacePost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_currentPlacePost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_currentPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_currentPost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_PostRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_PostRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ASPxRoundPanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel4 As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''cb_ippb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_ippb As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tb_ippb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_ippb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb_uidai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_uidai As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tb_uidai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_uidai As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb_cscid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_cscid As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tb_cscid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_cscid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb_pli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_pli As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tb_pli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_pli As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ASPxRoundPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel2 As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''emptrnsfGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emptrnsfGridView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''btn_add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_delete As Global.System.Web.UI.WebControls.Button
End Class
