'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System

Partial Public Class RegisterModule

    ''' <summary>
    ''' SignInRegisterTabControl control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected SignInRegisterTabControl As Global.DevExpress.Web.ASPxTabControl

    ''' <summary>
    ''' FormLayout control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected FormLayout As Global.DevExpress.Web.ASPxFormLayout

    ''' <summary>
    ''' RegisterUserNameTextBox control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RegisterUserNameTextBox As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' FirstNameTextBox control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected FirstNameTextBox As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' LastNameTextBox control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected LastNameTextBox As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' EmailTextBox control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected EmailTextBox As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' PasswordButtonEdit control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PasswordButtonEdit As Global.DevExpress.Web.ASPxButtonEdit

    ''' <summary>
    ''' ConfirmPasswordButtonEdit control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ConfirmPasswordButtonEdit As Global.DevExpress.Web.ASPxButtonEdit

    ''' <summary>
    ''' RegisterButton control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RegisterButton As Global.DevExpress.Web.ASPxButton
End Class