'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System

Partial Public Class SignInModule

    ''' <summary>
    ''' SignInRegisterTabControl control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected SignInRegisterTabControl As Global.DevExpress.Web.ASPxTabControl

    ''' <summary>
    ''' FormLayout control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected FormLayout As Global.DevExpress.Web.ASPxFormLayout

    ''' <summary>
    ''' UserNameTextBox control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected UserNameTextBox As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' PasswordButtonEdit control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PasswordButtonEdit As Global.DevExpress.Web.ASPxButtonEdit

    ''' <summary>
    ''' RememberMeCheckBox control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RememberMeCheckBox As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' GeneralErrorDiv control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected GeneralErrorDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    ''' <summary>
    ''' SignInButton control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected SignInButton As Global.DevExpress.Web.ASPxButton
End Class