'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class sbDeposit
    
    '''<summary>
    '''TableOfContentsTreeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableOfContentsTreeView As Global.DevExpress.Web.ASPxTreeView
    
    '''<summary>
    '''NodesDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NodesDataSource As Global.System.Web.UI.WebControls.XmlDataSource
    
    '''<summary>
    '''accIdTb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accIdTb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnFindAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFindAccount As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''balanceTb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents balanceTb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Acctypetb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Acctypetb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AccStatustb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccStatustb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ciftb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ciftb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''nametb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nametb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''nametb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nametb2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ASPxRoundPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel1 As Global.DevExpress.Web.ASPxRoundPanel
    
    '''<summary>
    '''photophoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents photophoto As Global.DevExpress.Web.ASPxImage
    
    '''<summary>
    '''CifInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CifInfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NameInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameInfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CifStatustb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CifStatustb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dobtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dobtb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''genderlb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents genderlb As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''mobiletb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobiletb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''emailtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailtb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pantb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pantb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''adhartb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adhartb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''addresstb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addresstb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''photosign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents photosign As Global.DevExpress.Web.ASPxImage
    
    '''<summary>
    '''DepositAmounttb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepositAmounttb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Calculatebtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calculatebtn As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''newbalancetb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newbalancetb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''transctiontb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents transctiontb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateofTransction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateofTransction As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dlttb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlttb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dlttb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlttb2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''detailstb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents detailstb As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button3 As Global.System.Web.UI.WebControls.Button
End Class
