'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DallyAccounts

    '''<summary>
    '''datetb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datetb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LinkButton4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''obtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents obtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''crdtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crdtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sbdtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbdtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rddtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rddtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdftb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdftb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ssadtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ssadtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ssaftb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ssaftb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tddtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tddtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rplidtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rplidtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rpliftb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpliftb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rplittb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rplittb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vppdtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vppdtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ippbdtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ippbdtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cscdtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cscdtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''totaldtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totaldtb As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''crwtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crwtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sbwtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbwtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdwtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdwtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ssawtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ssawtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tdwtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdwtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rpliwtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpliwtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''monwtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents monwtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ippbwtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ippbwtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''totalwithtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalwithtb As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cashtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cashtb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''stamptb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stamptb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''stamp2tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stamp2tb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''baltb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents baltb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''avbtb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents avbtb As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''btnnew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnnew As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btncalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncalculate As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnupdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnupdate As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btndelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndelete As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnprint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnprint As Global.DevExpress.Web.ASPxButton
End Class
